export const getSearchUsers = async () => {
  return [
    {
      id: 1,
      name: "Ramesh",
      email: "ramesh@in.com",
      country: "Colombia",
      status: true,
      admin: false,
    },
    {
      id: 2,
      name: "Rakesh",
      email: "rakesh@in.com",
      country: "Colombia",
      status: true,
      admin: false,
    },
    {
      id: 3,
      name: "Rajesh",
      email: "rajesh@in.com",
      country: "Colombia",
      status: true,
      admin: false,
    },
    {
      id: 4,
      name: "Rishan",
      email: "rajesh@in.com",
      country: "Colombia",
      status: true,
      admin: false,
    },
    {
      id: 5,
      name: "Nihil",
      email: "rajesh@in.com",
      country: "Colombia",
      status: true,
      admin: false,
    },
    {
      id: 6,
      name: "rocky",
      email: "rajesh@in.com",
      country: "Colombia",
      status: true,
      admin: false,
    },
    {
      id: 7,
      name: "albert",
      email: "rajesh@in.com",
      country: "Colombia",
      status: true,
      admin: false,
    },
  ];
};
